//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pasvlas
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idService { get; set; }
        public Nullable<int> idPatient { get; set; }
        public Nullable<System.DateTime> dateService { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> idUsers { get; set; }
    
        public virtual patients patients { get; set; }
        public virtual services services { get; set; }
        public virtual users users { get; set; }
    }
}
